# updated to include examples of text_layer, panning_layer, group_layer, and markup_layer
Sequence:
    - LastScores:
        Font: status
        FontStyle: default
        # Animation: dark_chrome
        # lampshow: attract_show_2
        # sound: sling
        duration: 2.0
# updated to include examples of text_layer, panning_layer, group_layer, and markup_layer
Sequence:
    - LastScores:
        Font: status
        FontStyle: default
        # Animation: dark_chrome
        # lampshow: attract_show_2
        # sound: sling
        duration: 2.0
    - ScriptedText:
        Name: scriptedText
        Font: high_score_entry_inits
        FontStyle: score_font_style
        Animation: trophy # If this is a single frame, the duration of the layer will be duration * messages....if not the duration of animation frames will be used
        duration: 2.0
        flashing: True
        #sound: intro
        TextOptions:           
          - Text: 
            - ""
            - ""
            - ""
            - "PUSH"
            - "START"
          - Text: []
          - Text:
            - ""
            - "TO"
            - "PLAY"       
    - Combo:
        Text:
            - "Author"
            - ""
            - "Presents"
        # Font: med  -- these are optional for 
        # FontStyle: weird  -- Combo layers
        # Animation: dark_chrome
        # lampshow: attract_show_2
        # sound: sling
        duration: 2.0
    - text_layer: # a more powerful version of the Combo Layer for text
        x: .50   # 50% of the display width
        y: .50    # 50% of the display height
        h_justify: center
        v_justify: center
        Text: "empty game"        
        Font: status
        duration: 1.0
    - text_layer: # a more powerful version of the Combo Layer for text
        x: .50   # 50% of the display width
        y: .50    # 50% of the display height
        h_justify: center
        v_justify: center
        Text: "PRESS START"        
        Font: status
        duration: 1.0
    - HighScores:
        Font: status
        FontStyle: default
        # Animation: dark_chrome
        Order:
            - player
            - category
            - score
        duration: 4.0 # increase duration since it is now the length of all high score frames, together!       
    - Combo:
        Text:
            - "Author"
            - ""
            - "Presents"
        # Font: med  -- these are optional for 
        # FontStyle: weird  -- Combo layers
        # Animation: dark_chrome
        # lampshow: attract_show_2
        # sound: sling
        duration: 2.0
    - text_layer: # a more powerful version of the Combo Layer for text
        x: .50   # 50% of the display width
        y: .50    # 50% of the display height
        h_justify: center
        v_justify: center
        Text: "empty game"        
        Font: status
        duration: 1.0
    - text_layer: # a more powerful version of the Combo Layer for text
        x: .50   # 50% of the display width
        y: .50    # 50% of the display height
        h_justify: center
        v_justify: center
        Text: "PRESS START"        
        Font: status
        duration: 1.0
    - HighScores:
        Font: status
        FontStyle: default
        # Animation: dark_chrome
        Order:
            - player
            - category
            - score
        duration: 1.0 # increase duration since it is now the length of all high score frames, together!