Trophys:
  'Welcome':
    description: 'Launched your first ball'
    completedDate: ''
    icon: 'trop_welcome'
  'FirstGame':
    description: 'Played your first game'
    completedDate: ''
    icon: 'trop_firstgame'    