Audits: {Avg Ball Time: '0:53', Avg Extra Balls: 0, Avg Game Time: '2:48', Avg Score: 0,
  Balls Played: 3, Games Played: 1, Games Started: 15, Total Game Time: 14.0, Longest Ball Time: 14.0}
ClassicHighScores:
- {inits: GSS, score: 500}
- {inits: ASP, score: 400}
- {inits: JRP, score: 300}
- {inits: JAG, score: 200}
- {inits: JTW, score: 100}
LoopsHighScoreData:
- {inits: GSS, score: 5}
